### PR TITLE
240: JSON Patch: Object not added at index specified in add op

### LINKED ISSUE #240: JSON Patch: Object not added at index specified in add op
Given an `add` operation that inserts a new object at some index of a containment reference, the new object is always appended to the containment list. The index is ignored.

e.g., given

```json
{
  "op": "add",
  "path": "/eClassifiers/3/eStructuralFeatures/2",
  "value": {
    "$type": "http://www.eclipse.org/.../EAttribute",
    "name": "newAttribute"
  }
}
```

the correct `EClass` is located in the classifiers list of the package, but if there are more than two features already in that class, the new attribute is always added at the end of the list of features, not inserted at index 2.

### PR DESCRIPTION
**Pull request by cdamus**
Insert at the index given by the path when an index is specified, for both `EReference`s and `EAttribute`s.

Fixes #240

Contributed on behalf of STMicroelectronics.

### CODE REVIEW

**Review by eneufeld — APPROVED** [review]
Thank you!

**Comment by cdamus** [comment]
Commit 0aacb66c7a392a99b04d8619d35482fa9af703d2 rebases the changes to resolve the merge conflict.

**Comment by cdamus** [comment]
And commit 2969f96b86421e35440ca47e91024dd510452e0f works around a compilation error caused by Hamcrest's broken generic type signatures.

**Review by eneufeld — APPROVED** [review]
Looks still great!

**Pull request merged**
