### PR TITLE
#140 Update to emfcloud.checkstyle 0.1.0-RC02

### LINKED ISSUE #140: Update checkstyle config to work with checkstyle 8.44
The m2e integration of the latest Eclipse release (2021-09) has a dependency to a version of the eclipse-checkstyle plugin that is using checkstlye v. 8.44. The current checkstyle config is based on 8.39 and is not compatible with this version. We should update our codestyle config to be compliant with the latest Eclipse Release. For a smoother transition we could keep the current checkstyle config as a fallback option.

### PR DESCRIPTION
**Pull request by tortmayr**
The new release candiate uses a ruleset that is compliant with Checkstyle 8.44 as default.
This ensures that the checkstyle config can also be used in the latest Eclipse Relaease (8.44).
If you don't use the latest Eclipse release it's still recommended to update to the latest eclipse-checkstyle plugin version. However, the old checkstyle config (8.39) is still available and can be set in the project-specific properties.

Fixes #140

### CODE REVIEW

**Comment by tortmayr** [comment]
Depends on https://github.com/eclipse-emfcloud/emfcloud/commit/5487a868947443346b0bb51e3a89d00793d72fba.
Currently CI Jobs are not executed. I have informed the Eclipse IT. Hopefully the deploy job will be executed soon

**Review by ndoschek — COMMENTED** [review]
Thanks Tobias! Basically the new checkstyle config works fine for me!
Although, there seems to be a problem if importing existing (Maven) projects. On importing, the `.checkstyle` file is changed (please see attached screenshot).
Also, the provided option in the preferences `Maven > Checkstyle > Allow Checkstyle to write formatter/cleanup config when importing projects` seems to have no effect.

image

**Comment by tortmayr** [comment]
Thanks for the review Nina. I addressed your review comments.

> Although, there seems to be a problem if importing existing (Maven) projects. On importing, the .checkstyle file is changed (please see attached screenshot).
Also, the provided option in the preferences Maven > Checkstyle > Allow Checkstyle to write formatter/cleanup config when importing projects seems to have no effect.

I cannot reproduce this problems. I also downloaded a fresh 2021-09 Modeling Tools package and tried to reproduce it in there.
For me everything works fine. However, I couple of other resources changed as well if I simply import all projects. To avoid future conflicts I opted to commit these changes.

BTW I also don't have the Maven-> Checkstyle option. Maybe you have an addtional plugin installed (looks like https://github.com/m2e-code-quality/m2e-code-quality to me).

**Review by ndoschek — APPROVED** [review]
Thanks a lot Tobias! I removed the m2e code quality plugin and now everything seems stable on my end! Also importing maven projects does not cause changes anymore.

**Pull request merged**
